{% set name = "liknorm" %}
{% set version = "1.4.3" %}
{% set sha256 = "ff6c40e9524d67e2eecce88e63d900ec786311d7e7fccf22bea3c118a7754db1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/liknorm/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - conda-build
  run:

test:
  commands:
    - test -e $PREFIX/include/liknorm.h  # [unix]
    - test -e $PREFIX/lib/libliknorm.so  # [linux]
    - test -e $PREFIX/lib/libliknorm.dylib  # [osx]
    - test -e $PREFIX/lib/libliknorm_static.a  # [unix]
    - if NOT exist %LIBRARY_INC%/liknorm.h exit 1  # [win]
    - if NOT exist %LIBRARY_LIB%/liknorm.lib exit 1  # [win]
    - if NOT exist %LIBRARY_BIN%/liknorm.dll exit 1  # [win]
    - if NOT exist %LIBRARY_LIB%/liknorm_static.lib exit 1  # [win]

about:
  home: https://github.com/limix/liknorm
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Moments of the product of an exponential-family likelihood with Normal distribution'
  doc_url: https://liknorm.readthedocs.io/
  dev_url: https://github.com/limix/liknorm

extra:
  recipe-maintainers:
    - Horta
