{% set name = "liknorm" %}
{% set version = "1.2.4" %}
{% set sha256 = "ebfd3ec617a274f5feaf6a64de1a6b90be434c75eb986b731fd4caa400d3bfed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glimix/liknorm/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win32 or linux32]

requirements:
  build:
    - python  # [win]
    - conda-build
    - toolchain
    - cmake

test:
  requires:
    - python  # [win]
  commands:
    - test -e $PREFIX/lib/libliknorm.so  # [linux]
    - test -e $PREFIX/lib/libliknorm_static.a  # [linux]
    - test -e $PREFIX/lib/libliknorm.dylib  # [osx]
    - test -e $PREFIX/lib/libliknorm_static.a  # [osx]
    - if NOT exist %PREFIX%/lib/liknorm.lib exit 1  # [win]
    - if NOT exist %PREFIX%/lib/liknorm_static.lib exit 1  # [win]

about:
  home: https://github.com/limix/liknorm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Moments of the product of an exponential-family likelihood with a Normal distribution'
  doc_url: https://liknorm.readthedocs.io/
  dev_url: https://github.com/limix/liknorm

extra:
  recipe-maintainers:
    - Horta
