{% set name = "liknorm" %}
{% set version = "1.3.2" %}
{% set sha256 = "6341b0545a156d150020b1ace961b9c85b14b60ecf0bf5284fabac31ba1cb57c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/liknorm/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python  # [win]
    - conda-build
    - toolchain
    - cmake
    - hcephes >=0.2.3  # [win and py27]

test:
  requires:
    - python  # [win]
  commands:
    - test -e $PREFIX/lib/libliknorm.so  # [linux]
    - test -e $PREFIX/lib/libliknorm_static.a  # [linux]
    - test -e $PREFIX/lib/libliknorm.dylib  # [osx]
    - test -e $PREFIX/lib/libliknorm_static.a  # [osx]
    - if NOT exist %PREFIX%/lib/liknorm.lib exit 1  # [win]
    - if NOT exist %PREFIX%/lib/liknorm.dll exit 1  # [win]
    - if NOT exist %PREFIX%/lib/liknorm_static.lib exit 1  # [win]

about:
  home: https://github.com/limix/liknorm
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Moments of the product of an exponential-family likelihood with Normal distribution'
  doc_url: https://liknorm.readthedocs.io/
  dev_url: https://github.com/limix/liknorm

extra:
  recipe-maintainers:
    - Horta
