# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QYpRnA2pcHxSWabNGn0xD9z7IMqm8l2Ma6dksoSG04/SyNnppdQLnBE6CpPp5qukKFrQfdUYrgGn6yNIzyBIqXwKIewszVDuhSe0ZCkdEXfvXjQVb2d+g/KC4BcgrPVtfLUyIM8MvKFfjH0TR4aa0YNC8wfHB3W0g04slH3IE74m+up+y9eaC/tn+ecfcXnA3p7NkW47Dxf0o6mH1rKC28BdW8Xn4oNfVJgJ+L3lJzbxblJZ/Cf5oPVRHQD8oacDJUMqWQDwSoifz+wEyqn3f7nkc6F/J4N5H3Rt5VrZwPgVGlBA6O/opH7DFQZt/QupLcjdwsa5ts40XUypEayLP3kR1b4gxxkRgiLnCR8wEs56WA514GGE9+Es+M5zjbSfG1V2V+RHfHifv3E4BhTKvdBZGxlNX1ttx1AHhfe/kkVda8AkqPVdfarptyhL91y3NFJqE7UN10TkzGywY23mTeA/UfJKlzI57jka47cq04++K4l22VbAuwMd5SIY5hY/LXQQ73H7w50BRi1FlRKI037mtiexNH6pZZSk2zxFEtVuwK0Zsv00++TcYKelLBf9SMzj+UFllcNACyv/scLHBUHMYypiLDL3zdCq2BU/EvC93X7fSFWlqUeK2kxLHffwGgTYCwLsY6XUMoDNUfyN7QRBzGXP4TZwEXBbb3EYVzg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
