travis:
  secure:
    BINSTAR_TOKEN: t0X7UlPIRdVoiGvE4DriWiM4sO5ZQxA2fNl8hQcvlCSR85BhQuKK6MFrs46x6RDSY4G86vYJDOnsZKeRkZ4HN6QKG5eq9PaIODwI9leHR33iaKhcG91M5gG5sOQyQSVtKphQD0q4f9Z0XfSfoDg/hIizRXUMEvQJ8a4bao+WrfuatUnoP6/dRzXbdO0/tbb15fXxfACfS8LcobkcFaD2VkO8At8Kix+Ork43CipvCzDV5tFy76WP3Bnz4Dh7LbFDbPmgQDb57Ycq7M0apl1yqdnC+pxJg4IK8XeUoIjLis/NcEEDo8c5d8DIZMjNFncvgN6o9SxzLuNKj0CIf3TrmCEevOyCUg0qDbujpSgpkt2oORswhaOo9etacbrRyg4eHxdO2TAHfnxz1pfPNQAjN1MMAkB331bEsGRNr8ISSAqhMMbSAm8ow9D7rUMrb7C0ETTJr2TPe7DkYm/UYd3p4uKhzUC9GeXopmW0L8Q5Y9cjcdTc7eLUMtxIOnOEyshdZP7xSI8kBc3qk9rw0Javpb5Cd/gwtvtF/K7bYNpmj0lRbtrzAF49BcUqVCeDPBicT/LIpHRlnTF9z/gdF5NKL4xTn+gzSX/SNqfcWj+Sdf7d21RWzmvbFrUApDOGM2UcQqzsO6DQJfV1rsdRDXMEor7R9SqWuqYHGs1w8GSnmSw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
